# Machine Learning Configuration for Cross-Sell Intelligence Platform

# Model ensemble configuration
ensemble:
  weights:
    neural_net: 0.3
    xgboost: 0.3
    random_forest: 0.2
    gradient_boost: 0.2
  
  voting_strategy: weighted

# Neural Network configuration
neural_network:
  architecture:
    hidden_layers: [64, 32, 16]
    activation: relu
    dropout_rate: 0.3
  
  training:
    learning_rate: 0.001
    batch_size: 32
    epochs: 50
    early_stopping_patience: 10
    validation_split: 0.2

# XGBoost configuration
xgboost:
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  subsample: 0.8
  colsample_bytree: 0.8
  objective: binary:logistic
  eval_metric: auc

# Random Forest configuration
random_forest:
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: sqrt
  bootstrap: true

# Gradient Boosting configuration
gradient_boost:
  n_estimators: 100
  max_depth: 5
  learning_rate: 0.1
  subsample: 0.8

# Feature engineering configuration
feature_engineering:
  numeric_features:
    - annual_revenue
    - number_of_employees
    - days_since_last_activity
    - company_age_days
  
  categorical_features:
    - industry
    - type
    - billing_country
    - rating

# Training configuration
training:
  test_size: 0.2
  random_state: 42
  cross_validation_folds: 5

# API configuration
api:
  cache_ttl_seconds: 60
